name: carwash
version: 3.10.1
publish_to: none
description: Mobile Car Wash Online.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  barcode_widget: ^2.0.3
  cupertino_icons: ^1.0.2
  data_table_2: ^2.3.7
  easy_sidemenu: 0.4.0
  flutter_tts: ^3.5.3
  fluttertoast: ^8.2.1
  get: 4.6.5
  http: ^0.13.5
  intl: ^0.17.0
  lottie: ^2.3.2
  path_provider: ^2.0.11
  bluetooth_print: ^4.3.0
  multiselect_formfield: ^0.1.7
  datetime_picker_formfield: ^2.0.1
  crypto: ^3.0.3
  printing: ^5.9.3
  pdf: ^3.8.4
  assets_audio_player: ^3.0.5
  
  ota_update: ^4.0.3
  flutter_speed_dial: ^6.3.0
  shared_preferences: ^2.1.1
  month_year_picker: 0.2.0+4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/logo.png
  web: 
    image_path: assets/logo.png
    background_color: '#hexcode'
    theme_color: '#hexcode'
    generate: true
  ios: true
  min_sdk_android: 21

flutter: 
  fonts: 
    - family: Nunito
      fonts: 
        - asset: assets/font/nunito/Nunito-Black.ttf
        - asset: assets/font/nunito/Nunito-BlackItalic.ttf
        - asset: assets/font/nunito/Nunito-Bold.ttf
        - asset: assets/font/nunito/Nunito-BoldItalic.ttf
        - asset: assets/font/nunito/Nunito-ExtraBold.ttf
        - asset: assets/font/nunito/Nunito-ExtraBoldItalic.ttf
        - asset: assets/font/nunito/Nunito-ExtraLight.ttf
        - asset: assets/font/nunito/Nunito-ExtraLightItalic.ttf
        - asset: assets/font/nunito/Nunito-Light.ttf
        - asset: assets/font/nunito/Nunito-Regular.ttf
  assets: 
    - assets/
    - assets/audio/
  uses-material-design: true

